name = "EvoLinear"
uuid = "ab853011-1780-437f-b4b5-5de6f4777246"
authors = ["jeremie <jeremie.desgagne.bouchard@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
